### ISSUE TITLE
Crash on /new mapping page when dataset permissions are denied

### ISSUE THREAD

**Issue by ericfranz** [OSC/shiny_admin#30]
```
App 119803 stdout: [2018-11-06 16:43:55 -0500 usr/PAS1429/shiny_admin]  INFO "method=GET path=/pun/usr/wiag/shiny_admin/mappings/new format=html controller=MappingsController action=new status=500 error='ActionView::Template::Error: Permission denied @ dir_initialize - /fs/project/PAS1429/data/osc/wiag/rnaseq_test_data' duration=82.04 view=0.00 db=0.00"
App 119803 stdout: [2018-11-06 16:43:55 -0500 usr/PAS1429/shiny_admin] FATAL "ActionView::Template::Error (Permission denied @ dir_initialize - /fs/project/PAS1429/data/osc/wiag/rnaseq_test_data):\n     8:   <%= f.select :app, app_list.map{ |uri| [get_app_name(uri), uri]}, :include_blank => true, help: app_list_help %>\n     9: \n    10:   <%= f.form_group :dataset, label: { text: 'Dataset (absolute path)' }, help: known_datasets_help do %>\n    11:     <% known_datasets.each do |dataset| %>\n    12:       <%= f.radio_button :dataset, dataset, label: dataset %>\n    13:     <% end %>\n    14:     <%= f.radio_button :dataset, 'dataset_non_std_location', label: 'Other' %>\n  app/helpers/mappings_helper.rb:41:in `block in installed_datasets'\n  app/helpers/mappings_helper.rb:38:in `installed_datasets'\n  app/helpers/mappings_helper.rb:56:in `known_datasets'\n  app/views/mappings/new.html.erb:11:in `block (2 levels) in _app_views_mappings_new_html_erb__2958711955019129585_29627540'\n  app/views/mappings/new.html.erb:10:in `block in _app_views_mappings_new_html_erb__2958711955019129585_29627540'\n  app/views/mappings/new.html.erb:4:in `_app_views_mappings_new_html_erb__2958711955019129585_29627540'"
```

**Comment by ericfranz** [comment]
The problem was the dataset directory was owned by the wrong project:

```
drwxrwx--- 3 efranz PZS0714 4096 Nov  6 16:25 /fs/project/PAS1429/data/osc/wiag/rnaseq_test_data/
```
